version: "3.9"
services:
  api:
    tty: true
    env_file:
    - api/.env 
    build: api
    ports:
      - "8080:8080"
    depends_on:
    - db
  db:
    tty: true
    image: mongo
    volumes:
    - "dbdata:/data/db"
    ports:
    - "27017:27017"

volumes:
   dbdata: